     
name: 05-3. Hello World JS

on: 
  [workflow_dispatch]

jobs:
      
  hello_world_js:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2

      - name: hello-action
        uses: ./.github/actions/hello-world-js
