name: 04-1. Call Reusable Workflow Templates

on:
  push:
     branches: [main]
  workflow_dispatch:  

jobs:
  call_reusable_workflow_job:
    uses: anu-01/nationwide-gh-actions/.github/workflows/greet-everyone.yml@main
    with:
      name: 'Reusable Workflow Templates'
    
  call_dependencies_workflow_job:
    needs: call_reusable_workflow_job
    uses: anu-01/nationwide-gh-actions/.github/workflows/job-dependencies.yml@main
